refactor(installer): Change how pkg mgr pck installation is shown

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,30 +3,43 @@
 # -----------------------###----------------------- #
 #                      THESIS                       #
 #                   ------------                    #
-#           A personal forward operating base       #
-#               and a Head in the Clouds            #
+#         A personal forward operating base         #
+#             and a Head in the Clouds              #
 # -----------------------###----------------------- #
 #                    LICENCE FIELD                  #
 # -----------------------###----------------------- #
 #                  TABLE OF CONTENTS                #
 #              -----------------------              #
+#   ~.      Functions                               #
 #   I.      Determening system's package manager    #
 #   II.     Install packages                        #
 #   III.    Stow symlinks                           #
 #   IV.     Setup zsh                               #
 # -----------------------###----------------------- #
 
-# Echo colored messages based on message type.
+# ---------- #
+# ~FUNCTIONS #
+# ---------- #
+
+###################################################
+# Echo signed and colored notifications.          #
+#                                                 #
+# Arguments:                                      #
+#   type        -   operation | success | failure #
+#   message     -   message to echo               #
+#   indent      -   true | false -> default=false #
+###################################################
 notify ()
 {
     # Parse arguments.
     local type=$1
     local message=$2
+    local indent=${3:-false}
 
     # Colours.
     local blue="\033[0;34m"
-    local green="\033[0;34m"
-    local red="\033[0;34m"
+    local green="\033[1;32m"
+    local red="\033[0;31m"
     local no_color="\033[0m"
     
     # Config.
@@ -35,7 +48,7 @@ notify ()
     
     # Deduce color and sign for the notification.
     case "$type" in
-        "operation") 
+        "operation")
             colour=$blue
             sign="[*] "
         ;;
@@ -54,14 +67,21 @@ notify ()
     esac
     
     # Echo notification.
-    echo -e "$colour$sign$message$no_color"
+    if [ $indent = true ];
+    then
+        echo -e "\t$colour$sign$message$no_color"
+    else
+        echo -e "$colour$sign$message$no_color"
+    fi
     
 }
-echo "--- THESIS ---"
+
 
 # ------------------------------------- #
 # I. DETERMINE SYSTEM'S PACKAGE MANAGER #
 # ------------------------------------- #
+
+echo "--- THESIS ---"
 
 # Declare a system -> package manager associative array.
 declare -A PM_LOOKUP=(
@@ -71,20 +91,21 @@ declare -A PM_LOOKUP=(
 # Determine package manager.
 PACKAGE_MANAGER="NONE"
 
+notify operation "Thesis is determining system's package manager"
 for file in ${!PM_LOOKUP[@]};
 do
-    echo "[*] Thesis is determining system's package manager"
     if [[ -f $file ]]; then
         PACKAGE_MANAGER=${PM_LOOKUP[$file]}
-        echo "[+] Thesis has found $PACKAGE_MANAGER"
+        notify success "Found $PACKAGE_MANAGER" true
         break
     fi
 done
 
 # Abort if no suitable package manager was found.
 if [ $PACKAGE_MANAGER = "NONE" ]; then
-    echo "[-] Thesis cannot determine the systems package manager"
-    echo "[*] Thesis is aborting installation ..."
+    notify failure "Cannot determine system's package manager" true
+    notify failure "Aborting installation ..."
+    echo "--- THESIS ---"
     exit 1
 fi
 
@@ -105,7 +126,9 @@ PACKAGES=(
     cargo       # Rust package manager.
 )
 
-echo "[*] Thesis is installing ${#PACKAGES[@]} packages ..."
+notify \
+    operation \
+    "Thesis is installing ${#PACKAGES[@]} $PACKAGE_MANAGER packages"
 
 # Associatice array for package manager installation commands.
 declare -A PMIC=(
@@ -113,10 +136,20 @@ declare -A PMIC=(
 )
 
 # Install packages.
-for package in ${PACKAGES[@]};
+PACKAGES_LEN=${#PACKAGES[@]}
+for (( i=0; i<$PACKAGES_LEN; i++ ));
 do
-    echo "[*] Thesis is installing $package"
-    eval "${PMIC[$PACKAGE_MANAGER]} $package" &> /dev/null
+    eval "${PMIC[$PACKAGE_MANAGER]} ${PACKAGES[$i]}" &> /dev/null
+    which ${PACKAGES[$i]} &> /dev/null
+    
+    if [ $? -eq 0 ];
+    then
+        notify success "${PACKAGES[$i]} \t($(( $i + 1 ))/$PACKAGES_LEN)" true
+    else
+        notify failure "${PACKAGES[$i]} \t($(( $i + 1 ))/$PACKAGES_LEN)" true
+        true
+    fi
+
 done
 
 # install pip packages.
